// Assembles the loadable extension in build/ (load build/manifest.json in
// about:debugging, or package it with `npx web-ext build -s build`).
//
//   node tools/build.mjs [--watch]
//
// - copies manifest, src/, icons/ (and inlines the icon into the indicator)
// - bundles the speech worker (transformers.js + onnxruntime-web) with esbuild
// - copies onnxruntime's WASM runtime, so nothing is fetched from a CDN
// - copies the bundled models listed in models/models.json ("bundled": true)
import { cp, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'build');
const ORT = join(ROOT, 'node_modules/onnxruntime-web/dist');
// transformers.js loads onnxruntime's "asyncify" build for the WASM backend.
const ORT_FILES = ['ort-wasm-simd-threaded.asyncify.mjs', 'ort-wasm-simd-threaded.asyncify.wasm'];

async function sameFile(a, b) {
  try {
    const [sa, sb] = await Promise.all([stat(a), stat(b)]);
    return sa.size === sb.size && sa.mtimeMs <= sb.mtimeMs;
  } catch {
    return false;
  }
}

async function copyIfChanged(from, to) {
  if (await sameFile(from, to)) return;
  await mkdir(dirname(to), { recursive: true });
  await cp(from, to, { preserveTimestamps: true });
}

export async function build() {
  // Sources are small: always replace them so deleted files don't linger.
  for (const dir of ['src', 'icons']) await rm(join(OUT, dir), { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  await cp(join(ROOT, 'manifest.json'), join(OUT, 'manifest.json'));
  // src/worker is bundled below rather than copied.
  await cp(join(ROOT, 'src'), join(OUT, 'src'), {
    recursive: true, filter: p => !p.startsWith(join(ROOT, 'src/worker')),
  });
  await cp(join(ROOT, 'icons'), join(OUT, 'icons'), { recursive: true });

  // Inline the icon into the indicator, so the page never has to load a
  // file from the extension (that would need web_accessible_resources).
  const icon = (await readFile(join(ROOT, 'icons/icon.svg'), 'utf8')).trim();
  const indicator = join(OUT, 'src/content/indicator.js');
  const src = await readFile(indicator, 'utf8');
  const marker = "  const ICON_SVG = '';";
  if (!src.includes(marker)) throw new Error('indicator.js: ICON_SVG marker not found');
  await writeFile(indicator, src.replace(marker, `  const ICON_SVG = ${JSON.stringify(icon)};`));

  await esbuild.build({
    entryPoints: [join(ROOT, 'src/worker/asr-worker.js')],
    outfile: join(OUT, 'dist/asr-worker.js'),
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'firefox140',
    // Readable output: AMO reviewers must be able to compare it with the
    // published library sources.
    minify: false,
    legalComments: 'inline',
    logLevel: 'warning',
  });

  for (const f of ORT_FILES) await copyIfChanged(join(ORT, f), join(OUT, 'vendor/ort', f));

  const { models } = JSON.parse(await readFile(join(ROOT, 'models/models.json'), 'utf8'));
  for (const [name, model] of Object.entries(models)) {
    if (!model.bundled) continue;
    for (const file of Object.keys(model.files)) {
      await copyIfChanged(join(ROOT, 'models', name, file), join(OUT, 'models', name, file));
    }
  }
  await writeFile(join(OUT, 'BUILD-INFO.txt'),
    'Generated by tools/build.mjs from the repository root. Do not edit.\n');
}

await build();
console.log(`built ${OUT}`);
